export { SharedModule } from './components/shared.module';
export { DetailsModalComponent } from './components/details-modal/details-modal.component';
export { FavoritesModalComponent } from './components/favorites-modal/favorites-modal.component';
export { HeaderComponent } from './components/header/header.component';
export { WrapperComponent } from './components/wrapper/wrapper.component';
export { NumberToStringPipe } from './pipes/number-to-string.pipe';
export { Owner } from './models/owner';
export { OwnerRaw } from './models/owner-raw';
export { SummarizeTextPipe } from './pipes/summarize-text.pipe';
export * from './utils/manage-subscriptions';
export * from './utils/navigation';
export { OwnersListComponent } from './components/owners-list/owners-list.component';